/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Index': RouteRecordInfo<'Index', '/', Record<never, never>, Record<never, never>>,
    'Calendar': RouteRecordInfo<'Calendar', '/calendar', Record<never, never>, Record<never, never>>,
    'CalendarSchedule': RouteRecordInfo<'CalendarSchedule', '/calendar-schedule', Record<never, never>, Record<never, never>>,
    'Compliance': RouteRecordInfo<'Compliance', '/compliance', Record<never, never>, Record<never, never>>,
    'Expenses': RouteRecordInfo<'Expenses', '/expenses', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'Insights': RouteRecordInfo<'Insights', '/insights', Record<never, never>, Record<never, never>>,
    'Invoice': RouteRecordInfo<'Invoice', '/invoice', Record<never, never>, Record<never, never>>,
    'Message': RouteRecordInfo<'Message', '/message', Record<never, never>, Record<never, never>>,
    'Orders': RouteRecordInfo<'Orders', '/orders', Record<never, never>, Record<never, never>>,
    'Payments': RouteRecordInfo<'Payments', '/payments', Record<never, never>, Record<never, never>>,
    'Payroll': RouteRecordInfo<'Payroll', '/payroll', Record<never, never>, Record<never, never>>,
    'Projects': RouteRecordInfo<'Projects', '/projects', Record<never, never>, Record<never, never>>,
    'Reports': RouteRecordInfo<'Reports', '/reports', Record<never, never>, Record<never, never>>,
    'Talents': RouteRecordInfo<'Talents', '/talents', Record<never, never>, Record<never, never>>,
    'Times': RouteRecordInfo<'Times', '/times', Record<never, never>, Record<never, never>>,
  }
}
