import { describe, it, expect } from 'vitest'
import { useColumnSlots } from '../hooks/useColumnSlots'
import type { TableColumn } from '../types'

describe('useColumnSlots', () => {
  const { getSlotName, hasSlot, isValidSlotName, getSlotInfo, processColumnSlots } = useColumnSlots()

  describe('getSlotName', () => {
    it('应该为 slot: true 返回正确的槽名', () => {
      const column: TableColumn = {
        name: '用户名',
        prop: 'userName',
        type: 'string',
        slot: true
      }

      const slotName = getSlotName(column)
      expect(slotName).toBe('column-userName')
    })

    it('应该为 slot: string 返回自定义槽名', () => {
      const column: TableColumn = {
        name: '状态',
        prop: 'status',
        type: 'string',
        slot: 'custom-status'
      }

      const slotName = getSlotName(column)
      expect(slotName).toBe('custom-status')
    })

    it('应该为未配置 slot 的列返回 null', () => {
      const column: TableColumn = {
        name: '邮箱',
        prop: 'email',
        type: 'string'
      }

      const slotName = getSlotName(column)
      expect(slotName).toBeNull()
    })
  })

  describe('hasSlot', () => {
    it('应该正确识别有槽的列', () => {
      const columnWithSlot: TableColumn = {
        name: '用户名',
        prop: 'userName',
        type: 'string',
        slot: true
      }

      const columnWithoutSlot: TableColumn = {
        name: '邮箱',
        prop: 'email',
        type: 'string'
      }

      expect(hasSlot(columnWithSlot)).toBe(true)
      expect(hasSlot(columnWithoutSlot)).toBe(false)
    })
  })

  describe('isValidSlotName', () => {
    it('应该验证有效的槽名', () => {
      expect(isValidSlotName('valid-slot')).toBe(true)
      expect(isValidSlotName('column_userName')).toBe(true)
      expect(isValidSlotName('customStatus')).toBe(true)
    })

    it('应该拒绝无效的槽名', () => {
      expect(isValidSlotName('')).toBe(false)
      expect(isValidSlotName('   ')).toBe(false)
      expect(isValidSlotName('slot@name')).toBe(false)
      expect(isValidSlotName('slot name')).toBe(false)
      expect(isValidSlotName('1slot')).toBe(false)
      expect(isValidSlotName('-slot')).toBe(false)
    })
  })

  describe('getSlotInfo', () => {
    it('应该返回正确的槽信息', () => {
      const columnWithAutoSlot: TableColumn = {
        name: '用户名',
        prop: 'userName',
        type: 'string',
        slot: true
      }

      const columnWithCustomSlot: TableColumn = {
        name: '状态',
        prop: 'status',
        type: 'string',
        slot: 'custom-status'
      }

      const columnWithoutSlot: TableColumn = {
        name: '邮箱',
        prop: 'email',
        type: 'string'
      }

      const autoSlotInfo = getSlotInfo(columnWithAutoSlot)
      const customSlotInfo = getSlotInfo(columnWithCustomSlot)
      const noSlotInfo = getSlotInfo(columnWithoutSlot)

      expect(autoSlotInfo).toEqual({
        hasSlot: true,
        slotName: 'column-userName',
        isValid: true,
        isAutoGenerated: true,
        isCustom: false
      })

      expect(customSlotInfo).toEqual({
        hasSlot: true,
        slotName: 'custom-status',
        isValid: true,
        isAutoGenerated: false,
        isCustom: true
      })

      expect(noSlotInfo).toEqual({
        hasSlot: false,
        slotName: null,
        isValid: false,
        isAutoGenerated: false,
        isCustom: false
      })
    })
  })

  describe('processColumnSlots', () => {
    it('应该正确处理列槽数组', () => {
      const columns: TableColumn[] = [
        {
          name: '用户名',
          prop: 'userName',
          type: 'string',
          slot: true
        },
        {
          name: '邮箱',
          prop: 'email',
          type: 'string'
        },
        {
          name: '状态',
          prop: 'status',
          type: 'string',
          slot: 'custom-status'
        },
        {
          name: '金额',
          prop: 'amount',
          type: 'number'
        }
      ]

      const result = processColumnSlots(columns)

      expect(result.slotMap.size).toBe(2)
      expect(result.slotNames).toEqual(['column-userName', 'custom-status'])
      expect(result.hasAnySlots).toBe(true)

      // 验证 slotMap 中的内容
      expect(result.slotMap.get('column-userName')).toBe(columns[0])
      expect(result.slotMap.get('custom-status')).toBe(columns[2])
    })

    it('应该处理没有槽的列', () => {
      const columns: TableColumn[] = [
        {
          name: '用户名',
          prop: 'userName',
          type: 'string'
        },
        {
          name: '邮箱',
          prop: 'email',
          type: 'string'
        }
      ]

      const result = processColumnSlots(columns)

      expect(result.slotMap.size).toBe(0)
      expect(result.slotNames).toEqual([])
      expect(result.hasAnySlots).toBe(false)
    })
  })
})