/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Index': RouteRecordInfo<'Index', '/', Record<never, never>, Record<never, never>>,
    'Access': RouteRecordInfo<'Access', '/access', Record<never, never>, Record<never, never>>,
    'ActiveLog': RouteRecordInfo<'ActiveLog', '/active-log', Record<never, never>, Record<never, never>>,
    'AIChat': RouteRecordInfo<'AIChat', '/ai-chat', Record<never, never>, Record<never, never>>,
    'Calendar': RouteRecordInfo<'Calendar', '/calendar', Record<never, never>, Record<never, never>>,
    'Compliance': RouteRecordInfo<'Compliance', '/compliance', Record<never, never>, Record<never, never>>,
    'DataLog': RouteRecordInfo<'DataLog', '/data-log', Record<never, never>, Record<never, never>>,
    'EmailLog': RouteRecordInfo<'EmailLog', '/email-log', Record<never, never>, Record<never, never>>,
    'ErrorLog': RouteRecordInfo<'ErrorLog', '/error-log', Record<never, never>, Record<never, never>>,
    'Expenses': RouteRecordInfo<'Expenses', '/expenses', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    '/home/cor/cChart': RouteRecordInfo<'/home/cor/cChart', '/home/cor/cChart', Record<never, never>, Record<never, never>>,
    '/home/cor/cTable': RouteRecordInfo<'/home/cor/cTable', '/home/cor/cTable', Record<never, never>, Record<never, never>>,
    '/home/cor/quick': RouteRecordInfo<'/home/cor/quick', '/home/cor/quick', Record<never, never>, Record<never, never>>,
    '/home/direct/dChart': RouteRecordInfo<'/home/direct/dChart', '/home/direct/dChart', Record<never, never>, Record<never, never>>,
    '/home/direct/dTable': RouteRecordInfo<'/home/direct/dTable', '/home/direct/dTable', Record<never, never>, Record<never, never>>,
    '/home/direct/quick': RouteRecordInfo<'/home/direct/quick', '/home/direct/quick', Record<never, never>, Record<never, never>>,
    '/home/eor/createEorEmployee': RouteRecordInfo<'/home/eor/createEorEmployee', '/home/eor/createEorEmployee', Record<never, never>, Record<never, never>>,
    '/home/eor/eChart': RouteRecordInfo<'/home/eor/eChart', '/home/eor/eChart', Record<never, never>, Record<never, never>>,
    '/home/eor/eTable': RouteRecordInfo<'/home/eor/eTable', '/home/eor/eTable', Record<never, never>, Record<never, never>>,
    '/home/eor/quick': RouteRecordInfo<'/home/eor/quick', '/home/eor/quick', Record<never, never>, Record<never, never>>,
    '/home/gpo/pChart': RouteRecordInfo<'/home/gpo/pChart', '/home/gpo/pChart', Record<never, never>, Record<never, never>>,
    '/home/gpo/pTable': RouteRecordInfo<'/home/gpo/pTable', '/home/gpo/pTable', Record<never, never>, Record<never, never>>,
    '/home/gpo/quick': RouteRecordInfo<'/home/gpo/quick', '/home/gpo/quick', Record<never, never>, Record<never, never>>,
    'Insights': RouteRecordInfo<'Insights', '/insights', Record<never, never>, Record<never, never>>,
    'Invoice': RouteRecordInfo<'Invoice', '/invoice', Record<never, never>, Record<never, never>>,
    'Message': RouteRecordInfo<'Message', '/message', Record<never, never>, Record<never, never>>,
    'Orders': RouteRecordInfo<'Orders', '/orders', Record<never, never>, Record<never, never>>,
    'Payments': RouteRecordInfo<'Payments', '/payments', Record<never, never>, Record<never, never>>,
    'Payroll': RouteRecordInfo<'Payroll', '/payroll', Record<never, never>, Record<never, never>>,
    'Projects': RouteRecordInfo<'Projects', '/projects', Record<never, never>, Record<never, never>>,
    'Reports': RouteRecordInfo<'Reports', '/reports', Record<never, never>, Record<never, never>>,
    'Roles': RouteRecordInfo<'Roles', '/roles', Record<never, never>, Record<never, never>>,
    'Talents': RouteRecordInfo<'Talents', '/talents', Record<never, never>, Record<never, never>>,
    'Times': RouteRecordInfo<'Times', '/times', Record<never, never>, Record<never, never>>,
    'Users': RouteRecordInfo<'Users', '/users', Record<never, never>, Record<never, never>>,
  }
}
