import type { TableColumn } from '../types'

/**
 * 列槽管理 Hook
 * 提供列槽名称生成和验证功能
 */
export function useColumnSlots() {
  /**
   * 生成列槽名称
   * @param column 列配置
   * @returns 槽名称
   */
  const getSlotName = (column: TableColumn): string | null => {
    if (!column.slot) {
      return null
    }

    // 如果是 true，自动生成槽名
    if (column.slot === true) {
      return `column-${column.prop}`
    }

    // 如果是字符串，直接使用
    if (typeof column.slot === 'string') {
      return column.slot
    }

    return null
  }

  /**
   * 检查列是否使用槽
   * @param column 列配置
   * @returns 是否使用槽
   */
  const hasSlot = (column: TableColumn): boolean => {
    return getSlotName(column) !== null
  }

  /**
   * 验证槽名称格式
   * @param slotName 槽名称
   * @returns 是否有效
   */
  const isValidSlotName = (slotName: string): boolean => {
    // 槽名称不能为空
    if (!slotName || slotName.trim() === '') {
      return false
    }

    // 槽名称不能包含特殊字符
    const invalidChars = /[^a-zA-Z0-9_-]/
    if (invalidChars.test(slotName)) {
      return false
    }

    // 槽名称不能以数字或连字符开头
    if (/^[0-9-]/.test(slotName)) {
      return false
    }

    return true
  }

  /**
   * 获取列槽配置信息
   * @param column 列配置
   * @returns 槽配置信息
   */
  const getSlotInfo = (column: TableColumn) => {
    const slotName = getSlotName(column)

    return {
      hasSlot: hasSlot(column),
      slotName,
      isValid: slotName ? isValidSlotName(slotName) : false,
      isAutoGenerated: column.slot === true,
      isCustom: typeof column.slot === 'string'
    }
  }

  /**
   * 批量处理列槽配置
   * @param columns 列配置数组
   * @returns 槽配置映射
   */
  const processColumnSlots = (columns: TableColumn[]) => {
    const slotMap = new Map<string, TableColumn>()
    const slotNames: string[] = []

    columns.forEach(column => {
      const slotInfo = getSlotInfo(column)
      if (slotInfo.hasSlot && slotInfo.isValid && slotInfo.slotName) {
        slotMap.set(slotInfo.slotName, column)
        slotNames.push(slotInfo.slotName)
      }
    })

    return {
      slotMap,
      slotNames,
      hasAnySlots: slotNames.length > 0
    }
  }

  return {
    getSlotName,
    hasSlot,
    isValidSlotName,
    getSlotInfo,
    processColumnSlots
  }
}