/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Index': RouteRecordInfo<'Index', '/', Record<never, never>, Record<never, never>>,
    'Access': RouteRecordInfo<'Access', '/access', Record<never, never>, Record<never, never>>,
    'ActiveLog': RouteRecordInfo<'ActiveLog', '/active-log', Record<never, never>, Record<never, never>>,
    'AIChat': RouteRecordInfo<'AIChat', '/ai-chat', Record<never, never>, Record<never, never>>,
    'Clients': RouteRecordInfo<'Clients', '/clients', Record<never, never>, Record<never, never>>,
    'DataLog': RouteRecordInfo<'DataLog', '/data-log', Record<never, never>, Record<never, never>>,
    'EmailLog': RouteRecordInfo<'EmailLog', '/email-log', Record<never, never>, Record<never, never>>,
    'Entity': RouteRecordInfo<'Entity', '/entity', Record<never, never>, Record<never, never>>,
    'ErrorLog': RouteRecordInfo<'ErrorLog', '/error-log', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'Insights': RouteRecordInfo<'Insights', '/insights', Record<never, never>, Record<never, never>>,
    'Location': RouteRecordInfo<'Location', '/location', Record<never, never>, Record<never, never>>,
    'Message': RouteRecordInfo<'Message', '/message', Record<never, never>, Record<never, never>>,
    'Projects': RouteRecordInfo<'Projects', '/projects', Record<never, never>, Record<never, never>>,
    'Reports': RouteRecordInfo<'Reports', '/reports', Record<never, never>, Record<never, never>>,
    'ReportDetail': RouteRecordInfo<'ReportDetail', '/reports/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Roles': RouteRecordInfo<'Roles', '/roles', Record<never, never>, Record<never, never>>,
    'ServiceType': RouteRecordInfo<'ServiceType', '/service-type', Record<never, never>, Record<never, never>>,
    'Users': RouteRecordInfo<'Users', '/users', Record<never, never>, Record<never, never>>,
  }
}
